Criação de esqueletos das classes Estatísticas(GUI) e Repositório de Projetos
pauloborba/tasksandtalks pull request #11
Opened 2020-11-13 04:26 UTC by amandascm

2020-11-13 10:47 UTC, pauloborba requested changes

2020-11-13 10:47 UTC, pauloborba commented on tnt-gui/src/app/estatisticas.component.ts
> +    selector: '',
@amandascm o nome do selector é uma importante parte da interface com outras pessoas da equipe. para referenciar esse componente, elas precisam do nome do selector. aí pode ser estatísticas

2020-11-13 10:47 UTC, pauloborba commented on tnt-server/repositorioDeProjetos.ts
> +export class repositorioDeProjetos {
um padrão muito comum é começar o nome da classe com maiúsculas. ajusta, por favor. nome de método começa com minúsculas.

2020-11-14 02:31 UTC, amandascm commented on tnt-gui/src/app/estatisticas.component.ts
> +    selector: '',
@pauloborba resolvido nos commits abaixo

2020-11-14 02:31 UTC, amandascm commented on tnt-server/repositorioDeProjetos.ts
> +export class repositorioDeProjetos {
@pauloborba ajustado nos commits abaixo

2020-11-14 13:25 UTC, merged