Adicionando esqueleto do Contexto(GUI) + Contexto(Serviço)
pauloborba/tasksandtalks pull request #4
Opened 2020-11-12 05:57 UTC by matheus29t

2020-11-12 12:43 UTC, pauloborba commented
@matheus29t define o nome do selector, e adiciona a contexto os atributos que temos no modelo DDD

2020-11-12 17:37 UTC, matheus29t commented
atualizado, o selector também foi definido.

2020-11-13 00:17 UTC, pauloborba requested changes

2020-11-13 00:17 UTC, pauloborba commented on common/contexto.ts
> +    eventos: boolean;
não existe eventos no DDD

2020-11-13 00:17 UTC, pauloborba commented on common/contexto.ts
> +    eventos: boolean;
existe Evento, subclasse de Contexto

2020-11-13 00:50 UTC, matheus29t commented on common/contexto.ts
> +    eventos: boolean;
Devo importar, no código, a classe "Evento" que vai ser criada por Humberto no arquivo "evento.ts" da common ou deixo sem o import?
Mais uma coisa, no DDD, o atributo de contexto está escrito "Eventos", isso deve ser implementado na classe "Contexto" como "evento: Evento" ou "eventos: Evento"?

2020-11-13 01:16 UTC, pauloborba commented on common/contexto.ts
> +    eventos: boolean;
colocaria o import só se voce fosse referenciar Evento nessa classe, mas isso não parece ser necessário.

em que DDD? no meu não está assim. não existe esse atributo.

2020-11-13 01:23 UTC, matheus29t commented on common/contexto.ts
> +    eventos: boolean;
Estou me guiando pelo [DDD colaborativo que está no slack](https://docs.google.com/drawings/d/1Jv_YMwYs_spV3WwDx9YYBohgGdGOxW1supKVGu5njRk/edit), não é esse?
Devo só remover esse atributo então?

2020-11-13 01:26 UTC, pauloborba commented on common/contexto.ts
> +    eventos: boolean;
o DDD base é o que eu expliquei em aula e está pinado no canal do slack, a imagem. qualquer mudança nele que não tenha sido discutida no slack, deve ser desconsiderada

2020-11-13 12:34 UTC, pauloborba approved these changes

2020-11-13 12:35 UTC, merged